name: 'Execute data structure unit tests.'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distributions: 'adopt'
      - name: 'Run tests with maven'
        run: 'mvn test'
